### ISSUE TITLE
[10.0] bae_report_to_printer More detail Guidance / Manual needed

### ISSUE THREAD

**Issue by bunhin** [OCA/report-print-send#106]
Dear All,

I want to use base_report_to_printer module, and have go to the "run bot" to try,  please inform do i need to setup something in the client machine / browser before i can add the printer to the server and then can print the report?  I try to add the server but always get connection error message.

Please help

Thank you

**Comment by lasley** [comment]
@bunhin - This is a highly technical module that detailed documentation does not exist for at this time. 

From your issue description, I gather you are trying to test the module on Runbot. In order to use this module, you need a CUPS server - and your Odoo server needs to be able to talk to it. Runbot should not be able to talk to any CUPS server you have setup, so that means you would need to test this locally.

Sorry but I'm closing this issue - documentation for this module primarily falls in scope of properly setting up a CUPS server. The module itself is a simple install + config, and works great on numerous production deploys.
