### ISSUE TITLE
Use Qz tray

### ISSUE THREAD

**Issue by saxomanu** [OCA/report-print-send#243]
Hi !
I'm working with logistic plateform, and use base_report_to_printer to send zpl label to printer.
But we need a cups server in printer's network. 
So we use a rapsberry to do the job.
Generaaly Odoo server is outside the printer's networ, so we need also a VPN.
So we need a lot of prerequisites, it's cost time, and heavy infrastructure.

I have in my plan to do the job with QZ (https://qz.io).
We have just have to install qz on client side for work.

What do you think about this ?
Can someone help me ?

Thx.

**Comment by angelmoya** [comment]
Any news with QZ try, I also would like to test it.

I have several servers working with cups to print ZPL labels, and it's hard to mantain, so I would like to test QZ try, for the begining to POS tickets.

**Comment by angelmoya** [comment]
Finally I did an alternative to base_report_to_printer bassed on QZ Tray.

This month I plan to tested, but works nice, also with certificates and without promt warnings.

Only we need to detect automatically local printers.

And maybe could be nice to do a base module base_report_to_printer, and inherit base_report_to_printer_cups and base_report_to_printer_qztray... because the module I'm developing will be in conflict with base_report_to_printer.

**Comment by angelmoya** [comment]
Also, it works with raw print for escpos

**Comment by angelmoya** [comment]
I push module on #270
